### ISSUE TITLE
Nice Work

### ISSUE THREAD

**Issue by mmaaz60** [OpenGVLab/InternVideo#1]
Hi, Thanks for the great work

When are you planning to release the code? Thanks

**Comment by shepnerd** [comment]
The code and model weights will be released in the following two weeks. The training and evaluation codes will come first along with models in the medium size (e.g. vit-base). The larger ones need more review time.

**Comment by rugrag** [comment]
looking forward for it! can't wait to try it

**Comment by BigJoon** [comment]
Haven't you posted it yet?
