### ISSUE TITLE
Simple question: What are the public datasets included in InternVid-200M?

### ISSUE THREAD

**Issue by jong980812** [OpenGVLab/InternVideo#100]
In "InternVid: A Large-scale Video-Text Dataset for Multimodal Understanding and Generation," I would like to use ViCLIP-B-16 on InternVid-200M. Does this dataset ( or InternVid-FLT)  contain videos from Kinetics400, SSV2, and UCF101? It is not clearly written in your paper whether only the labels were referred to, or if the videos were also included. I am curious to know

**Comment by shepnerd** [comment]
It **does not** contain videos from your mentioned datasets. We clearified it in Sec. 3.1 data curation as follows:"We ensure the uniqueness of our dataset by creating a database of YouTube video IDs and excluding any videos already present in publicly available datasets (released prior to April 2023)."
