### ISSUE TITLE
will you release pretrained model of InternVideo2-s2-1B frame=8?

### ISSUE THREAD

**Issue by 1093842024** [OpenGVLab/InternVideo#103]
thank you for the great work!

I'm working on video and audio multimodel understanding work, and want to use your model as my base model for experiments.

Beside the released InternVideo2-s2-1B frame=4, the contrast experiments also need InternVideo2-s2-1B frame=8.

wish to get  the following release plan and updates!

best wish!

**Comment by chinmayad** [comment]
Will you be releasing  InternVideo2-s2-1B models soon? Want to use this as baseline for some zero-shot action recognition experiments.

**Comment by leexinhao** [comment]
Please see https://github.com/OpenGVLab/InternVideo/blob/a6ba0548f619df4fdefe08d5ba5808abe7462741/InternVideo2/multi_modality/models/backbones/internvideo2/pos_embed.py#L185 

You could use it to make `InternVideo2-s2-1B frame=4` get a 8 frames input.

**Comment by 1093842024** [comment]
> Please see
> 
> https://github.com/OpenGVLab/InternVideo/blob/a6ba0548f619df4fdefe08d5ba5808abe7462741/InternVideo2/multi_modality/models/backbones/internvideo2/pos_embed.py#L185
> 
> You could use it to make `InternVideo2-s2-1B frame=4` get a 8 frames input.

thanks a lot

**Comment by chinmayad** [comment]
Thanks. This link in hugging face is broken 
https://huggingface.co/OpenGVLab/InternVideo2/blob/main/InternVideo2-stage2_1b-224p-f4.pt 

Can you please fix it?

**Comment by leexinhao** [comment]
> Thanks. This link in hugging face is broken https://huggingface.co/OpenGVLab/InternVideo2/blob/main/InternVideo2-stage2_1b-224p-f4.pt
> 
> Can you please fix it?

Please visit https://huggingface.co/OpenGVLab/InternVideo2-Stage2_1B-224p-f4
