### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Hari-Durai-Baskar** [OpenGVLab/InternVideo#108]
Hi do you have any docker image for s2 inference? 
for some reason i need to build a docker container for inference or use an available docker image for the same.

**Comment by shepnerd** [comment]
Hi there! At this time, we don't have a dedicated Docker image for S2 inference, but we're actively working on making it easier to deploy S2 in various environments. We appreciate your patience as we continue to improve the accessibility of S2.

**Comment by prashant-dn** [comment]
Found this working for `OpenGVLab/InternVideo2_5_Chat_8B`. 

Use container `docker pull huggingface/transformers-pytorch-gpu:latest` with local CUDA 12.1+.

Inside, just install 'flash attention', if needed, using `pip install flash-attn --no-build-isolation`.

Works like a charm!
