### ISSUE TITLE
where is /eval_msrvtt_no_deepspeed.sh for s2 evaluation?

### ISSUE THREAD

**Issue by Hari-Durai-Baskar** [OpenGVLab/InternVideo#109]
I could not find the file scripts/evaluation/stage2/zero_shot/1B/eval_msrvtt_no_deepspeed.sh in the repo. Is it removed? if so pls update the readme accordingly

**Comment by leexinhao** [comment]
Try set `enable=False` in https://github.com/OpenGVLab/InternVideo/blob/533cf9aed2937c97d07d07e1082d0e14c7760faf/InternVideo2/multi_modality/scripts/evaluation/stage2/zero_shot/1B/config_msrvtt.py#L145
