### ISSUE TITLE
What is the difference between model internvideo2_s2 and internvideo2_clip?

### ISSUE THREAD

**Issue by lllllllll-3154** [OpenGVLab/InternVideo#113]
Hello, thank you for your work. I checked the huggingface model in https://github.com/OpenGVLab/InternVideo/blob/main/InternVideo2/multi_modality/MODEL_ZOO.md, I am wondering what exactly [InternVideo2-Stage2_1B-224p-f4] and [InternVideo2-CLIP-1B-224p-f8] are, why the previous one is almost 3GB while the later one is only 14mb? Which one is the video encoder that will be used in the third stage in your paper? Thank you.

**Comment by Andy1621** [comment]
Hi! The `CLIP` one is finetuned from `Stage2` to support more applications (with powerful [InternVL](https://github.com/OpenGVLab/InternVL/tree/main) text encoder). As for `Stage3`, it is further trained with `Stage2` checkpoint.

**Comment by Andy1621** [comment]
As for the checkpoint size, we only tune the `AttnPool` in visual encoder for `CLIP`, thus the trainable parameters are small.

**Comment by lllllllll-3154** [comment]
Thank you for your answer

**Comment by Eliza-and-black** [comment]
> As for the checkpoint size, we only tune the `AttnPool` in visual encoder for `CLIP`, thus the trainable parameters are small.关于检查点大小，我们只为 `CLIP` 的视觉编码器中的 `AttnPool` 进行调整，因此可训练参数较少。
Hi! Ｈow to use InternVideo2-CLIP-1B-224p-f8 in video retrieval task?

**Comment by Eliza-and-black** [comment]
> As for the checkpoint size, we only tune the `AttnPool` in visual encoder for `CLIP`, thus the trainable parameters are small.

Hi! Ｈow to use InternVideo2-CLIP-1B-224p-f8 in video retrieval task?
