### ISSUE TITLE
Download InternVid Dataset Issues

### ISSUE THREAD

**Issue by yh675** [OpenGVLab/InternVideo#117]
Hello, thanks for the great work!

I am trying to download the InternVid 10M Dataset through yt-dlp but it seems that YouTube blocks the IP address fairly quickly, after maybe 30-50 thousand video clip downloads.

How did you get around this problem of YouTube blocking the ip address or throttling the downloading speed?

Thanks.

**Comment by shepnerd** [comment]
Try [this site](https://opendatalab.com/vd-foundation/InternVid-10M-FLT/cli/main).
