### ISSUE TITLE
InternVideo1: Cannot load videos using petrel_client for Video-Text Retrieval task

### ISSUE THREAD

**Issue by ruixuan-ray-zhang** [OpenGVLab/InternVideo#118]
I have been trying to run zero-shot evaluation code wth main_task_retrieval on MSRVTT dataset. I found that in Video-Text-Retrieval/dataloaders/dataloader_msrvtt_retrieval.py line 16
`from petrel_client.client import Client` couldn't be executed and caused error in line 143 `video_bytes = client.get(video_path, enable_stream=True)` because now `client = None`.

I tried to install `petrel_client` but didn't find any resources online. How did you guys get the reproduction results? Thanks!

**Comment by Andy1621** [comment]
You can simply remove it and read it by decord.

**Comment by ruixuan-ray-zhang** [comment]
Thanks for your reply! After I figured out it was just an image-loading function, I did exactly the same thing but forgot to close the issue. I am closing it now. Thank you again.
