### ISSUE TITLE
Why do i get this load-checkpoint as a list of False values? 

### ISSUE THREAD

**Issue by Hari-Durai-Baskar** [OpenGVLab/InternVideo#123]
Load-checkpoint for vision encoder shows a list containing bool False. Why is this behavior observed?
![image](https://github.com/OpenGVLab/InternVideo/assets/97948393/4c65cad8-bf9e-45e1-ae63-5dd2d88b8f48)

**Comment by Andy1621** [comment]
Hi! It's a list for whether using gradient checkpoint.
