### ISSUE TITLE
Test evaluation on Something-Something v2

### ISSUE THREAD

**Issue by yujiangpu20** [OpenGVLab/InternVideo#132]
Thank you for the excellent work. I noticed that the test labels of the SS-v2 dataset are not accessible, how did you get the test results? Are the results reported in the paper conducted on the validation set? Thanks!

**Comment by Andy1621** [comment]
Yes. The reported results on ours and other papers are for validation set~

**Comment by yujiangpu20** [comment]
Got it. Thank you!
