### ISSUE TITLE
 LSMDC Annotation Files 

### ISSUE THREAD

**Issue by fmthoker** [OpenGVLab/InternVideo#137]
Dear authors, can you share the annotation files that are used for LSMDC retrieval? I am trying to reproduce the results using ViClip models but it's not clear which annotation files were used. Thanks in advance.

**Comment by JingXiaolun** [comment]
@fmthoker ，sorry to disturb you. When I reproduce the LSMDC results, I find the MeanR is always around 200, I use the 2016 splits (101046 for training, 7408 for validation , and 1000 for test),  and the video is compressed to 3fps (224x224). Do you encounter similar problems? Looking forward to your reply.

**Comment by fmthoker** [comment]
@JingXiaolun please check this issue [lsmdc](https://github.com/OpenGVLab/InternVideo/issues/139)
