### ISSUE TITLE
Request access of pre-trained mae model in open set action recognition model 

### ISSUE THREAD

**Issue by khm159** [OpenGVLab/InternVideo#14]
Hello.

First of all, thank you for sharing this great work.

I'm trying to use the openset action recognition, 
could I get Google Drive access to the pretrained MAE model?

Thank you.

**Comment by BigJoon** [comment]
Me too~~~. 
Could i get Google Drive Access to the pretrained MAE model too??

Thanks.

**Comment by shepnerd** [comment]
please refer to https://github.com/OpenGVLab/InternVideo#model-zoo for downloading.
