### ISSUE TITLE
Download scripts for InternVid-Aesthetics-18M dataset

### ISSUE THREAD

**Issue by SystemErrorWang** [OpenGVLab/InternVideo#140]
Thank you for your incredible works！
I would like to use the InternVid-Aesthetics-18M dataset to train some video generation models, but didn't find any available instruction or documentation of how to download it. Would you please provide a download script or instruction for it? Thank you

**Comment by sunwei925** [comment]
I also want to use the InternVid-Aesthetics-18M dataset.

**Comment by shepnerd** [comment]
Apologies for the delayed response. Please refer to [this link](https://huggingface.co/datasets/OpenGVLab/InternVid/viewer/InternVid-18M-AES).
