### ISSUE TITLE
Request to release multimodal finetuning for Internvideo2

### ISSUE THREAD

**Issue by Varun-GP** [OpenGVLab/InternVideo#149]
I request Authors to release finetuning for Internvideo2 model with multimodality: [https://github.com/OpenGVLab/InternVideo/tree/main/InternVideo2/multi_modality#finetuning](multimodal-finetuning)

**Comment by Andy1621** [comment]
Hi! For retrieval and QA, you can use those finetuning code in [UMT](https://github.com/OpenGVLab/unmasked_teacher).
