### ISSUE TITLE
How to get stage1 training data

### ISSUE THREAD

**Issue by qianwangn** [OpenGVLab/InternVideo#151]
It seems need 1.1M.tsv In scripts/pretraining/1B_pt.sh.
the format should like:  # line format: source, path, total_time, start_time, end_time, target
but the [UniFormerV2] provide # line format: path, id
so where can I get 1.1M.tsv

**Comment by Andy1621** [comment]
Hi. Please the this [file](https://drive.google.com/file/d/1wL7gQwrTEE0CVMz0-8avYxLKY1IabVKH/view?usp=sharing).
