### ISSUE TITLE
InternVideo2 models

### ISSUE THREAD

**Issue by orxh** [OpenGVLab/InternVideo#157]
Hi InternVideo team,

If I want to use a pretrained stage 1 InternVideo2 model for zero-shot or linear-probing video understanding tasks, which of the classes under https://github.com/OpenGVLab/InternVideo/tree/main/InternVideo2/single_modality/models is the correct one?

Thank you!

**Comment by leexinhao** [comment]
That's right!

**Comment by orxh** [comment]
Sorry If I was not clear enough.

I meant to ask which specific class should be used as a video encoder with pretrained models?

https://github.com/OpenGVLab/InternVideo/blob/main/InternVideo2/single_modality/models/internvideo2.py
or https://github.com/OpenGVLab/InternVideo/blob/main/InternVideo2/single_modality/models/internvideo2_pretrain.py?

Thank you!
