### ISSUE TITLE
Unable to download the Pretrained weights of VideoMAEv2-g

### ISSUE THREAD

**Issue by vinayvivek** [OpenGVLab/InternVideo#161]
I have filled out [VideoMAE V2 Download Request Form](https://docs.google.com/forms/d/e/1FAIpQLSd1SjKMtD8piL9uxGEUwicerxd46bs12QojQt92rzalnoI3JA/viewform?usp=sf_link)
and got one VideoMAE V2 Model Weight Links spreadsheet in which there are model weights in the Checkpoint column but after trying to download the weights from the given paths it's giving a NoSuchBucket error and I'm not able to download the Pretrained weights of VideoMAEv2-g.
I'm trying to download the model from this specific link that I got after filling out the form 
(https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/internvideo/videomaev2/vit_g_hybrid_pt_1200e.pth)
Can you please help me in this regard?

![image](https://github.com/user-attachments/assets/a9999fd0-c1f0-487b-af62-1b99ad8daf65)

**Comment by yinanhe** [comment]
Hi, these models have been moved to huggingface, you can download them on huggingface.

[pretrain model](https://huggingface.co/OpenGVLab/InternVideoMAE_models/resolve/main/mae-g/vit_g_hybrid_pt_1200e.pth)

[k710ft](https://huggingface.co/OpenGVLab/InternVideoMAE_models/resolve/main/mae-g/vit_g_hybrid_pt_1200e_k710_ft.pth)

[ssv2ft](https://huggingface.co/OpenGVLab/InternVideoMAE_models/resolve/main/mae-g/vit_g_hybrid_pt_1200e_ssv2_ft.pth)

**Comment by vinayvivek** [comment]
Certainly! Thank you for your prompt response.
