### ISSUE TITLE
How can I get the video files in the internvid dataset?

### ISSUE THREAD

**Issue by feitao-NB** [OpenGVLab/InternVideo#162]
Thank authors! This is a great dataset and great paper.

I tried to get the dataset. However, the files I downloaded from huggingface only contain the file ID and some meta information. Where can I get the video files? Download directly from youtube with the file ID? If some videos are no longer available, how can I replicate the result for comparison?

Thank you.

**Comment by yinanhe** [comment]
You can find data shared by third parties in opendatalab.com

**Comment by feitao-NB** [comment]
> You can find data shared by third parties in opendatalab.com

Thanks. I see the InternVid-full dataset. But still, I only see the json file in it and DON'T see the video files. Where can I get the video files?

Thank you once again.

**Comment by feitao-NB** [comment]
Thanks. Got it.
