### ISSUE TITLE
Demo中路径

### ISSUE THREAD

**Issue by hlchen23** [OpenGVLab/InternVideo#169]
Internvideo2中的demo中涉及到的PATH，分别每个PATH是对应的哪个文件？

**Comment by yinanhe** [comment]
可以直接参考这里的readme页面，需要使用到的有Mistral-7B的config文件，bert的config文件，和模型文件https://huggingface.co/OpenGVLab/InternVideo2_chat_8B_HD

**Comment by hlchen23** [comment]
您的来件已收到，谢谢！（自动回复）Chen

**Comment by hlchen23** [comment]
您的来件已收到，谢谢！（自动回复）Chen
