### ISSUE TITLE
CODE FOR VIDEOCHAT2 + INTERNVIDEO1B

### ISSUE THREAD

**Issue by Divyanshupy** [OpenGVLab/InternVideo#172]
Dear Team,
Thank you for the great work. I was wondering if you can share the stage3 training/inference code. I am aware its available on huggingface card but code available in the repository will offer more flexibility. 

Thank you and looking forward for the reply.

**Comment by yinanhe** [comment]
Inference code You can clone the code on huggingface to the local and modify it. 

The training code can refer to https://github.com/OpenGVLab/Ask-Anything/tree/main/video_chat2 for modification.
