### ISSUE TITLE
Request for checkpoint. I meet error

### ISSUE THREAD

**Issue by jong980812** [OpenGVLab/InternVideo#177]
<img width="804" alt="스크린샷 2024-09-11 오후 11 06 03" src="https://github.com/user-attachments/assets/48852fcf-ae9c-4658-9884-e42d484306cc">

I want to obtain this checkpoint, but I get an error. The model name is InternVideo1’s Downstream task K400. Could you provide the .pth file?

https://github.com/OpenGVLab/InternVideo/tree/main/InternVideo1

**Comment by shepnerd** [comment]
You can verify this new download [link](https://huggingface.co/OpenGVLab/InternVideo1.0/tree/main/internvideomae_classification).
