### ISSUE TITLE
Request for Video Instance Segmentation code and model

### ISSUE THREAD

**Issue by Becomebright** [OpenGVLab/InternVideo#178]
Thank you for your great work!

Could you please share the code and fine-tuned model for Video Instance Segmentation? This would be very helpful.

**Comment by rkzheng99** [comment]
The code for fine-tuning on VIS please refer to ViT-adapter and its efficient version that is used in DVIS++ (https://github.com/zhang-tao-whu/DVIS_Plus/tree/main/DVIS_Plus/configs/dvis_Plus/ytvis19/vit_adapter).

**Comment by Becomebright** [comment]
Thank you very much. I’ll take a look at it.
