### ISSUE TITLE
Downstream classification task checkpoint link not working

### ISSUE THREAD

**Issue by MH-Python** [OpenGVLab/InternVideo#179]
I am trying to download a downstream classification task model (VideoMAE-L K700) but got this instead:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
<RequestId>66E40608641DD935366F31E7</RequestId>
<HostId>pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com</HostId>
<BucketName>pjlab-gvm-data</BucketName>
<EC>0015-00000101</EC>
<RecommendDoc>https://api.aliyun.com/troubleshoot?q=0015-00000101</RecommendDoc>
</Error
```

Is there any code snippet or notebook showing how I can create a model from the .pth file and then use it on video clips to get the last features before the K400 classification layer?
Thank you

**Comment by yinanhe** [comment]
For easier access, we have uploaded the model to huggingface. The model can be found at [hf](https://huggingface.co/OpenGVLab/InternVideo1.0/tree/main/internvideomae_classification)

**Comment by mustafahalimeh** [comment]
Thank you so much for the quick reply.
Would you kindly provide an example how to load an .pth file and use it on a video to get the predicions probabilities (e.g. [vit_l_hybrid_pt_800e_k700_ft.pth]).

**Comment by AyeChmnmg** [comment]
<Error>

<Code>NoSuchBucket</Code>

<Message>The specified bucket does not

exist</Message>

<BucketName>api-2104.ppgames.net</BucketName>

<RequestId>NS36VCKENKH201MC</RequestId>

<HostId>nRqskW9a9MQ6HClbIHIie0qwTu3pw3ct75WhnZ0igi3Jc1Tki3aH4qXLVCSqjvLc2sjIF2NoL4s=

</HostId>

</Error>

**Comment by AyeChmnmg** [comment]
https://github.com/OpenGVLab/InternVideo/issues/179#issuecomment-2509925429

**Comment by yinanhe** [comment]
> [#179 (comment)](https://github.com/OpenGVLab/InternVideo/issues/179#issuecomment-2509925429)

@AyeChmnmg you can get the file from https://huggingface.co/OpenGVLab/InternVideo1.0/resolve/main/internvideomae_classification/vit_l_hybrid_pt_800e_k700_ft.pth
