### ISSUE TITLE
Guidance for CLIP-Based Model Re-initialization for Multi-Modal Model

### ISSUE THREAD

**Issue by CountingClouds** [OpenGVLab/InternVideo#18]
Hi Intern team,
Seeking your guidance on how to initialize the multi-modal-contrastive model from CLIP only, so that I can perform some multi-modal training experiments with just CLIP/Uniformer initialization, and not use Intern weights yet.

** Here is what I've attempted:

- I downloaded the aliyun multimodal checkpoint (just for shapes, layers, etc., but not the weights) from your [provided link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/internvideo/pretrain/InternVideo-MM-B-16.ckpt)
- I [extracted](https://github.com/OpenGVLab/UniFormerV2/blob/d390105e588665af5029bfcceed5b9975d4b13bb/extract_clip/extract.ipynb) CLIP B16 weights from [openaipublic](https://openaipublic.azureedge.net/clip/models), as instructed in the Uniformer library.
- I ran build_model from [here](https://github.com/OpenGVLab/InternVideo/blob/635c058ace710de5b93c26ebf8d9b1ee11556733/Pretrain/Multi-Modalities-Pretraining/InternVideo/clip_utils/model.py#L248), except the following modifications:
- I formed the layer definitions based off of the shapes, etc. of your provided model checkpoint. However, instead of also using that to load the weights, I instead use model.load_state_dict(state_dict, strict=False) using the CLIP B16 checkpoint instead.
- (Any weights not contained in the CLIP checkpoint are intended to be reinitialized from scratch, like you all did for your original MM experiments).

** Here were the results:

- The loading of CLIP weights doesn't work.  It seems that each of the weights in B16 CLIP model has consistently somewhat larger  dimension size
- The long list of errors illustrating this includes examples such as:  `size mismatch for transformer.resblocks.0.attn.in_proj_weight: copying a param with shape torch.Size([2304, 768]) from checkpoint, the shape in current model is torch.Size([1536, 512])`,  `size mismatch for transformer.resblocks.0.attn.in_proj_bias: copying a param with shape torch.Size([2304]) from checkpoint, the shape in current model is torch.Size([1536])`, etc.

** Hypothesis:

- The CLIP B16 model does not match what was used in the aliyun InternVideo MM B16 checkpoint

** Requested Guidance:

- Can you provide: 1) why the CLIP B16 model weights are not loading into InternVideo B16, 2) if my approach for CLIP-only initialization is correct, and 3) What model file I should use to get CLIP loaded into MultiModal InternVideo based off of your B16 checkpoint?

**Comment by liyz15** [comment]
Hello, from the error message, the model is not built correctly with embedding size 512, which should be 768 for B16 model. Please check the vision width [here](https://github.com/OpenGVLab/InternVideo/blob/635c058ace710de5b93c26ebf8d9b1ee11556733/Pretrain/Multi-Modalities-Pretraining/InternVideo/clip_utils/model.py#L307).

Also, if you are only looking for the vision encoder, you can try [UnifromerV2](https://github.com/OpenGVLab/UniFormerV2).

**Comment by CountingClouds** [comment]
Thank you ilyz.
I have new clues on what's going on.

I loaded and compared CLIP B16 weights dict and Intern MM B16 weights dict and found the following:

1) Intern MM B16 state dict has 368 elements to it; CLIP B16 state dict has only only 149.  
  * Hypothesis:  Is this CLIP file containing just the visual ViT layers and none of the text Transformer layers?

2) The shapes of parameters in the the CLIP layers, when compared against the same key in the Intern MM layers, match up exactly if we manipulate the names: It seems Intern MM has prepended the prefix "visual." to the ViT layers, but this prefix is not present in CLIP ViT layers.
  * Did Intern rename layers by adding a prefix?

If the above is all correct, then the CLIP file is missing its text embedding weights and I need to adjust for name manipulation with the prefix.  Does this all seem correct?

**Comment by CountingClouds** [comment]
Ah - I see where the issue is.  I just tried downloading CLIP directly from the OpenAI [github page](https://github.com/openai/CLIP) rather than using the instructions for CLIP extraction from UniformerV2.  It looks like the latter just downloads the ViT version, and with the manipulated (non-prefix) names for the layers.  Instead- the official CLIP contains both text transformer layers and visual transformer layers, 302 in total, which is what is expected.

**Comment by CountingClouds** [comment]
Yeah, confirmed.  I found it in the Uniformer code - it's manipulating the names (removing the "visual." prefix" and throwing away the text transformer data.  You can see it in the notebook [here](https://github.com/OpenGVLab/UniFormerV2/blob/d390105e588665af5029bfcceed5b9975d4b13bb/extract_clip/extract.ipynb).

All set then, this resolves my issue to know what was going on and how to fix it.
