### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by yepzhang** [OpenGVLab/InternVideo#180]
你好，请问你们的模型支持中文的回答吗？谢谢～

**Comment by shepnerd** [comment]
支持，但模型的中文回答能力依赖于使用的llm的中文能力。我们的开源模型的多模态训练过程中没加入中文标注。

**Comment by WeizhenEricFang** [comment]
> 支持，但模型的中文回答能力依赖于使用的llm的中文能力。我们的开源模型的多模态训练过程中没加入中文标注。

请问使用默认的-mistralai--Mistral-7B-Instruct-v0.3可以返回中文输入吗？我使用该默认llm，在model.chat()当中输入的是中国问提示词返回的仍然是英文。
