### ISSUE TITLE
Error 'NoneType' object is not callable when finetuning which is located in line 272 in './InternVideo2/single_modality/models/internvideo2.py'

### ISSUE THREAD

**Issue by Jenny199099** [OpenGVLab/InternVideo#187]
Hi author, thank you for your great work. I have encountered a problem when I finetuned Internvideo. In line 272 of "./InternVideo2/single_modality/models/internvideo2.py", the function "FusedMLP" returns a NoneType value. It relates to the flash_attn module. Could you please check this part? Thank you.

**Comment by yinanhe** [comment]
Please ensure that the fusedmlp module of Flash_attn is correctly installed. After installing flash_attn, you need to enter the directory to compile layer_norm separately.
```shell
cd csrc/layer_norm && pip install . && cd ../../ \
```
See [this comment](https://github.com/Dao-AILab/flash-attention/issues/587#issuecomment-1773565555) for details.

**Comment by Jenny199099** [comment]
> Please ensure that the fusedmlp module of Flash_attn is correctly installed. After installing flash_attn, you need to enter the directory to compile layer_norm separately.
> 
> ```shell
> cd csrc/layer_norm && pip install . && cd ../../ \
> ```
> 
> See [this comment](https://github.com/Dao-AILab/flash-attention/issues/587#issuecomment-1773565555) for details.

Thank you for your reply. I have done this to compile the layer_norm module. It is successfully installed. But the problem of FusedMLP still exists.

**Comment by yinanhe** [comment]
Sorry for misunderstanding your point. Have you compiled and installed fused_dense_lib from [this link](https://github.com/Dao-AILab/flash-attention/tree/main/csrc/fused_dense_lib)?

**Comment by Jenny199099** [comment]
> Sorry for misunderstanding your point. Have you compiled and installed fused_dense_lib from [this link](https://github.com/Dao-AILab/flash-attention/tree/main/csrc/fused_dense_lib)?

It works for me. Thank you very much.

**Comment by yinanhe** [comment]
Thank you for your timely feedback. If you have any questions, feel free to open this issue at any time :)

**Comment by suhyeok-jang** [comment]
Thank you
