### ISSUE TITLE
RuntimeError: Unknown model (pretrain_mae_base_patch16_224)

### ISSUE THREAD

**Issue by koren-v** [OpenGVLab/InternVideo#19]
Hi, guys, thanks a lot for a such good paper.

I wanted to investigate your model, but faced with mentioned in the title error from `timm` when I tried to run `Pretrain/VideoMAE/run_mae_vis.py`

**Comment by koren-v** [comment]
and yes, I have not found `timm==0.4.8` only `0.4.12`

**Comment by yinanhe** [comment]
It's in [Pretrain/VideoMAE/modeling_pretrain.py](https://github.com/OpenGVLab/InternVideo/blob/321b1bae403ddd391b679cb086cf2ae1a1ceaa6f/Pretrain/VideoMAE/modeling_pretrain.py). 

For timm, you can use `pip install timm==0.4.8`

**Comment by koren-v** [comment]
Hmm, thanks for your answer, will try!

**Comment by taqta** [comment]
Hi, thanks for your great work. 
I met the same error when I try to  run  run_videomae_vis.py, and I get the error below:

    RuntimeError: Unknown model (vit_huge_patch16_224)

and I try     

    pip install timm ==0.4.8

but get the error below:

    ERROR: Could not find a version that satisfies the requirement timm==0.4.8 (from versions: 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.8, 0.1.10, 0.1.12, 0.1.14, 0.1.16, 0.1.18, 0.1.20, 0.1.22, 0.1.24, 0.1.26, 0.1.28, 0.1.30, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.5, 0.4.9, 0.4.12, 0.5.4, 0.6.2.dev0, 0.6.5, 0.6.7, 0.6.11, 0.6.12, 0.8.0.dev0, 0.8.2.dev0, 0.8.3.dev0, 0.8.6.dev0, 0.8.10.dev0, 0.8.11.dev0)
    ERROR: No matching distribution found for timm==0.4.8

**Comment by yinanhe** [comment]
think this may be a Python version issue. Try updating to the another Python version.
