### ISSUE TITLE
action recognition code

### ISSUE THREAD

**Issue by zwxu064** [OpenGVLab/InternVideo#20]
Hi, where is the action recognition code for Table 1 in the paper, that is "Action recognition results on Kinetics & Something-Something"? Thanks.

**Comment by yinanhe** [comment]
You can temporarily refer to https://github.com/OpenGVLab/UniFormerV2

**Comment by zwxu064** [comment]
> You can temporarily refer to https://github.com/OpenGVLab/UniFormerV2

Thank you, but UniFormerV2 seems to have a huge performance gap from the InternVideo which achieves several sota in action recognition.

**Comment by yinanhe** [comment]
We add a model interaction using cross-model attention in Masked Video Encoder(MAE) and Multimodal Video Encoder which is based on UniFomerV2. The model with the largest number of parameters has not yet been public. You can try it yourself ~
