### ISSUE TITLE
使用hugging  face给的例子报错

### ISSUE THREAD

**Issue by cheun726** [OpenGVLab/InternVideo#209]
![image](https://github.com/user-attachments/assets/ee46f680-8590-410c-8788-2cd4d6d6901b)
![image](https://github.com/user-attachments/assets/69e5fc85-1546-4685-b965-73eb582f8579)
我使用huggging face给的demo例子，我将模型等文件下载到本地。报错。我检查您的原始文件，发现并没有 报错的这个文件。请帮我解决一下
![image](https://github.com/user-attachments/assets/de894cc8-f6fd-46a0-a45d-e8a7aa5bd695)

**Comment by yinanhe** [comment]
您好，在这段代码中会加载internlm2的相关config，请确保您的机器有可以访问到huggingface的网络，如果没有的话，可以提前下载internlm2除了safetensor之外的其他的文件并把config中的语言模型的路径指向您的本地缓存。https://huggingface.co/OpenGVLab/InternVideo2_Chat_8B_InternLM2_5/blob/main/modeling_base.py#L136-L143
