### ISSUE TITLE
Data augmentation used for Multi-Modalities-Pretraining

### ISSUE THREAD

**Issue by MikeWangWZHL** [OpenGVLab/InternVideo#21]
Thanks for sharing this great work!

In the `load_video` function in `Pretrain/Multi-Modalities-Pretraining/InternVideo/internvideo.py` I can find some video transforms that seems to be for inference. Is there anywhere I can find the similar transforms used during training? (e.g., leveraging other functions in the video_transform.py like ColorDistortion)

Thanks in advance!

**Comment by liyz15** [comment]
Hello, thanks for trying out InternVideo!

Currently the full training code for pre-training is not released. Only inference is released in `Pretrain/Multi-Modalities-Pretraining`.

You can refer to the downstream code for augmentation when training and we only use random spatial crop.

https://github.com/OpenGVLab/InternVideo/blob/635c058ace710de5b93c26ebf8d9b1ee11556733/Downstream/multi-modalities-downstream/CoTrain/transforms/video/videoaug.py#L13-L22

**Comment by MikeWangWZHL** [comment]
I see, thanks for the pointer!
