### ISSUE TITLE
作者大大

### ISSUE THREAD

**Issue by xiyangyang99** [OpenGVLab/InternVideo#211]
作者大大，你们测试过和cogVLM-video2在视频理解任务上的对比吗？

**Comment by leexinhao** [comment]
看了一下在MVBench上是比我们弱一些的，另外我们月底左右会放出更强一版的sota模型，欢迎后续关注

**Comment by xiyangyang99** [comment]
> 看了一下在MVBench上是比我们弱一些的，另外我们月底左右会放出更强一版的sota模型，欢迎后续关注

希望作者大大可以把多模态的时间敏感度考虑到后面的版本中去。强时序性的视频理解任务。
