### ISSUE TITLE
InternVideo/Downstream/Video-Text-Retrieval/modules/clip_evl/bpe_simple_vocab_16e6.txt.gz

### ISSUE THREAD

**Issue by RotEveryDay** [OpenGVLab/InternVideo#22]
it‘s not a gzip compressed data. I have solved it by copy clip4clip.

**Comment by wufeim** [comment]
Had the same issue. Fixed by taking `bpe_simple_vocab_16e6.txt.gz` from [here](https://github.com/openai/CLIP/blob/main/clip/bpe_simple_vocab_16e6.txt.gz).
