### ISSUE TITLE
Minor issue in the ViT3D script

### ISSUE THREAD

**Issue by zhang-jr** [OpenGVLab/InternVideo#3]
Thanks for sharing your nice job.

some minor issue was found here.

The variable `num_classes` in [`get_classifier`](https://github.com/OpenGVLab/InternVideo/blob/dedb5915f4ce20634dd852f4e1c19169c216654b/Downstream/Open-Set-Action-Recognition/mmaction/models/backbones/ViT3D.py#L275) is undefined. Compared with the function [`reset_classifier`](https://github.com/MCG-NJU/VideoMAE/blob/718cdd0ad50525b3c8edab49b52605fbde73e3d6/modeling_finetune.py#L257), there should have an additional argument `num_classes`. By the way, in my mind, an API named `get_xx` should return a property of the `visionTransformer3D`. It may be useless in the current version, but it still needs a fix in the next version.

**Comment by hjzhang-forward** [comment]
Thanks for your attention, we will fix it soon.
