### ISSUE TITLE
could you please tell me how do you extract the thumos14 dataset from videoMAE

### ISSUE THREAD

**Issue by Value-Jack** [OpenGVLab/InternVideo#31]
Do you extract the flow feature and the rgb feature of the thumos14  by using the videoMAE and embedding them ?   or you just extract the rgb feature 1280 dim?

**Comment by Richard-61** [comment]
Just rgb feature.

**Comment by Value-Jack** [comment]
I only get 768 dim not 1280 dim

**Comment by Value-Jack** [comment]
- [ ]
