### ISSUE TITLE
How to check predicted label?

### ISSUE THREAD

**Issue by panzo2** [OpenGVLab/InternVideo#39]
I'm using Zero-shot action recognition.
I would like to check the predicted labels for the test videos after performing the identification. How can I do that?

**Comment by liyz15** [comment]
Thank you for trying out InternVideo!

Sorry we do not provide a direct way to get predicted labels. You can try to modify the [objective for zero-shot action recognition](https://github.com/OpenGVLab/InternVideo/blob/0df66a6ba3613469b4eb3602b4f556422b432c12/Downstream/multi-modalities-downstream/CoTrain/modules/objectives.py#L1323) to log the predicted labels.
