### ISSUE TITLE
How to obtain video url for instruction data

### ISSUE THREAD

**Issue by YunxinLi** [OpenGVLab/InternVideo#40]
I have traversed the Widvideo dataset and still cannot find a corresponding URL for some data. Can you provide a download URL for the instrument data?

**Comment by shepnerd** [comment]
You can refer to [here](https://github.com/m-bain/webvid#faqs-) that we cannot directly share these videos due to legal issues. If the number of videos you cannot download is relatively small, please do not worry about its influence on your final performance.
