### ISSUE TITLE
How to synthesize the comprehensive video description in InternVid?

### ISSUE THREAD

**Issue by SCZwangxiao** [OpenGVLab/InternVideo#48]
The paper says "These individual image captions are then synthesized into a comprehensive video description using a pretrained language model."

In the paper, it is unclear how the individual image captions are synthesized into a comprehensive description. Could you please share more details?

**Comment by yinanhe** [comment]
As shown in Figure2 of the paper, we use Image Caption Models to analyze video frames and generate image descriptions. These descriptions are subsequently fed into [T5](https://huggingface.co/mrm8488/flan-t5-large-finetuned-openai-summarize_from_feedback), which has been pre-trained on summarization tasks, for further summarization.
