### ISSUE TITLE
InternVid pretrained ViCLIP model

### ISSUE THREAD

**Issue by atao99** [OpenGVLab/InternVideo#51]
Hi,

The link to the pre-trained ViCLIP model in this [page](https://github.com/OpenGVLab/InternVideo/tree/main/Data/InternVid) seems to be invalid. Could you please update it?

Thank you.

**Comment by shepnerd** [comment]
We update it [here](https://github.com/OpenGVLab/InternVideo/tree/main/Data/InternVid#pretrained-data--model).
