### ISSUE TITLE
 Action Recognition's checkpoints do not exist

### ISSUE THREAD

**Issue by Yaofang-Liu** [OpenGVLab/InternVideo#52]
Hi, the checkpoints for the task "Open Set Action Recognition" do not exist. Please fix, many thanks.

**Comment by mustafahalimeh** [comment]
I am also can not find them
Is this permanent now? And are there any alternatives?

**Comment by shepnerd** [comment]
The ckpts of InternVideo-B/-L/-H are updated. Refer to https://github.com/OpenGVLab/InternVideo/tree/main/Downstream/Open-Set-Action-Recognition#model-zoo

**Comment by mustafahalimeh** [comment]
Thank you so much for your quick response.
But would you kindly provide a practical example of how to load the ckpt into an PyTorch model and retrain only the last layer.
Thanks in advance.
