### ISSUE TITLE
Model Zoo check points are not available

### ISSUE THREAD

**Issue by mustafahalimeh** [OpenGVLab/InternVideo#53]
Greetings,
It seems that all the the check points (pre-trained models) in the Model Zoo of this page:
https://github.com/OpenGVLab/InternVideo/tree/main/Downstream/Open-Set-Action-Recognition

are not available anymore, please provide a feedback regarding if they will be available again or not.
Thanks.

**Comment by mustafahalimeh** [comment]
I found a retrained model available:
https://github.com/OpenGVLab/InternVideo/tree/main#model-zoo
But when I try to load it with PyTorch it returns dict object, so would you give an example how to used a pre-trained model.
model = torch.load('vit_b_hybrid_pt_800e_k710_ft.pth')

**Comment by shepnerd** [comment]
The ckpts of InternVideo-B/-L/-H are updated. Refer to https://github.com/OpenGVLab/InternVideo/tree/main/Downstream/Open-Set-Action-Recognition#model-zoo

**Comment by mustafahalimeh** [comment]
Thank you so much for your quick response.
But would you kindly provide a practical example of how to load the ckpt into an PyTorch model and retrain only the last layer.
Thanks in advance.
