### ISSUE TITLE
Checkpoint of VideoChat-ViCLIP

### ISSUE THREAD

**Issue by yellow-binary-tree** [OpenGVLab/InternVideo#57]
Thank you for providing this nice work!
In Section 5.3 of the paper you mentioned that you trained a **VideoChat-ViCLIP model** by replacing the video encoder of VideoChat-Embed into ViCLIP. I suppose that some extra parameters (GMHRA, extra_query_tokens, linear layer, according to VideoChat paper)  are needed to incorporate a visual encoder into VideoChat. **Where can I find this checkpoint, as well as the code to load it?**

**Comment by shepnerd** [comment]
The related code is currently undergoing a cleaning process to ensure its usability and readability. We plan on releasing it alongside the dataset for a complete package that will facilitate your work.

In the meantime, we encourage you to explore our [Ask-Anything](https://github.com/OpenGVLab/Ask-Anything) repository. It contains valuable resources that you might find useful for your current needs. Please feel free to reach out if you have any questions or need further assistance.
