### ISSUE TITLE
Unable to download pretrained weights

### ISSUE THREAD

**Issue by bignfuse** [OpenGVLab/InternVideo#58]
Whenever, I try to download a pre-trained model. The downloading site cannot be reached.

**Comment by bignfuse** [comment]
This whole is website is not reachable : https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/

**Comment by shepnerd** [comment]
We are trying to isolate the issue and identify which part is broken. At this moment, your given website is inaccessible.
 On the other hand, we confirm that some checkpoint links from the model zoo (for instance, [InternVideo-MM](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/internvideo/pretrain/InternVideo-MM-L-14.ckpt)) are working perfectly fine in our tests. These checkpoints were downloaded successfully.

Could you please clarify further about the specific issues you're facing with these [download sites](https://github.com/OpenGVLab/InternVideo#model-zoo)? Are all of them causing trouble for you?
