### ISSUE TITLE
ViCLIP - Max Token Length 32 only?

### ISSUE THREAD

**Issue by Ericxgao** [OpenGVLab/InternVideo#59]
Hi, 

Traditionally CLIP is is 77 tokens, but ViCLIP weights only seem to support 32 - is this intentional?

Thanks,.

**Comment by shepnerd** [comment]
Yes. Most captions in our dataset are shorter than 32, hence we deliberately trim the training captions to 32 for efficiency. During evaluation, we only increase this hyperparameter to handle the ActivityNet dataset.
