### ISSUE TITLE
What is the prompt for the LLM to summarize?

### ISSUE THREAD

**Issue by xiefan233** [OpenGVLab/InternVideo#61]
> Technically, we employ the lightweight image captioning model Tag2Text [59] for the finer scale, which describes videos at low fps in a frame-by-frame manner. These individual image captions are then synthesized into a comprehensive video description using a pretrained language model [60, 61].

**Comment by yinanhe** [comment]
We use a pretrained T5 for summarize without any prompt.

**Comment by xiefan233** [comment]
> We use a pretrained T5 for summarize without any prompt.

What dataset did you use to train T5, or did you use the official T5-base directly?

**Comment by shepnerd** [comment]
We use the offical T5-summary without further finetuning, accessible at [this URL](https://huggingface.co/mrm8488/flan-t5-large-finetuned-openai-summarize_from_feedback).
