### ISSUE TITLE
Full dataset release

### ISSUE THREAD

**Issue by Caselles** [OpenGVLab/InternVideo#62]
Hello, 

First of all thank you for the great repository. 

I wonder if you will release the complete InternVid dataset ? I know that you released the 10M clips here https://huggingface.co/datasets/OpenGVLab/InternVid, it would be great to have access to the full dataset.

Thanks in advance for the answer and keep up the great work :)

**Comment by shepnerd** [comment]
Thank you for your interest in our work. We will release the full dataset within two weeks as we are checking dataset bias and safety.

**Comment by Caselles** [comment]
Wonderful news, thank you so much!
