### ISSUE TITLE
Cannot find the videos

### ISSUE THREAD

**Issue by wangyu-ustc** [OpenGVLab/InternVideo#63]
Dear Sir,

I want to use the dataset from https://github.com/OpenGVLab/Ask-Anything/tree/main/video_chat but I cannot find the link to the videos, there seem to be annotations here. Are the videos from Webvid? In this case, the format "000001_000050/1066682446.mp4" doesn't seem to match with the webvid annotations, I'll appreciate it so much if you could give me some hints! 

Thanks!
Best,
Yu

**Comment by shepnerd** [comment]
Your given case '000001_000050/1066682446.mp4' is the relative path of a video from WebVid10M. This dataset is structured like the following:

**Comment by icemoon-creative** [comment]
我想问一下是不是1066682446.mp4是唯一的，因为我只下载了部分的webvid数据集，想根据已经有的视频对
videochat_instruct_11k.json进行过滤一下。

**Comment by williamium3000** [comment]
Webvid dataset is no longer available. Is it possible that you can share the videos of 11k dataset in a zip file?

**Comment by yinanhe** [comment]
[videochat_instruct_11k_withurl.json](https://github.com/user-attachments/files/16373299/videochat_instruct_11k_withurl.json)

**Comment by williamium3000** [comment]
thank you
