### ISSUE TITLE
Download only English Portion of InternVID

### ISSUE THREAD

**Issue by LengSicong** [OpenGVLab/InternVideo#66]
Hi, may I know is there any way to download part of the videos from InternVID, that only using English instead of other languages? 

Or, if I can find the country/language info of the video somewhere?

**Comment by shepnerd** [comment]
We will release the required metainfo soon. If you download the original videos from YouTube, you can find the corresponding info in their meta.

**Comment by yinanhe** [comment]
Hi, we have added the `Language` dimension and `Category` dimension to [HuggingFace](https://huggingface.co/datasets/OpenGVLab/InternVid-10M-FLT-INFO).
