### ISSUE TITLE
When will you release ViCLIP-B/16?

### ISSUE THREAD

**Issue by jong980812** [OpenGVLab/InternVideo#67]
Same title. Can you provide a pretrained model ViT-B/16?. Thank you for your work.

**Comment by shepnerd** [comment]
We trained ViT-B only on InternVid-10M-FLT and InternVid-200M. We will be releasing it in the upcoming days. Stay tuned for the official release!

**Comment by shepnerd** [comment]
We have released the corresponding model weights [here](https://github.com/OpenGVLab/InternVideo/tree/main/Data/InternVid#pretrained-data--model) and made necessary updates to the demo code.
