### ISSUE TITLE
Training scripts for ViCLIP on InternVideo

### ISSUE THREAD

**Issue by XuecWu** [OpenGVLab/InternVideo#68]
Thank you for your great work! Could you please provide the training scripts of ViCLIP on InternVideo or other codebase that can be referenced for training?

**Comment by shepnerd** [comment]
Absolutely! We are currently in the process of cleaning the relevant code for the upcoming release. ViCLIP, which is a video implementation of CLIP with mask learning, has been developed on top of the Vindlu codebase. We are excited to share this enhanced version with you in the coming days. Stay tuned for the official release!

**Comment by XuecWu** [comment]
Thank you for your reply! Looking forward to the release of the updated codebase.
