### ISSUE TITLE
Error in loading `ViCLIP-L_InternVid-200M.pth`

### ISSUE THREAD

**Issue by dragen1860** [OpenGVLab/InternVideo#69]
Hi, I succeed to load `ViClip-InternVid-10M-FLT.pth`, but when try to load `ViCLIP-L_InternVid-200M.pth`, Error occured.
```
In [2]: a=torch.load("ViCLIP-L_InternVid-200M.pth")
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 a=torch.load("ViCLIP-L_InternVid-200M.pth")

File /media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/torch/serialization.py:809, in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    807             except RuntimeError as e:
    808                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 809         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    810 if weights_only:
    811     try:

File /media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/torch/serialization.py:1172, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1170 unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1171 unpickler.persistent_load = persistent_load
-> 1172 result = unpickler.load()
   1174 torch._utils._validate_loaded_sparse_tensors()
   1176 return result

File /media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/torch/serialization.py:1165, in _load.<locals>.UnpicklerWrapper.find_class(self, mod_name, name)
   1163         pass
   1164 mod_name = load_module_mapping.get(mod_name, mod_name)
-> 1165 return super().find_class(mod_name, name)

ModuleNotFoundError: No module named 'utils'

```

besides, the checkpoint size is also different.   `ViClip-InternVid-10M-FLT.pth` has only 1.7GB, but `ViCLIP-L_InternVid-200M.pth` has 4.1GB SIZE.  anyone know how to load 200M checkpoint?

**Comment by shepnerd** [comment]
It appears that the 'utils' module is missing from your working folder. To resolve this, please try copying the 'utils' module from [https://github.com/OpenGVLab/InternVideo/tree/main/Data/InternVid/viclip](https://github.com/OpenGVLab/InternVideo/tree/main/Data/InternVid/viclip) into your working directory. Let us know if you encounter any further issues.

**Comment by LiuHuijie6410** [comment]
> It appears that the 'utils' module is missing from your working folder. To resolve this, please try copying the 'utils' module from https://github.com/OpenGVLab/InternVideo/tree/main/Data/InternVid/viclip into your working directory. Let us know if you encounter any further issues.

Hello! I did not find the utils module under https://github.com/OpenGVLab/InternVideo/tree/main/Data/InternVid/viclip. Could you tell me the specific location of utils?

**Comment by yinanhe** [comment]
Since you didn't provide more error information, I guess it may come from this folder. https://github.com/OpenGVLab/InternVideo/tree/main/Data/InternVid/utils
