### ISSUE TITLE
Difference between FLT, DIV and AES of InternVid

### ISSUE THREAD

**Issue by Hambaobao** [OpenGVLab/InternVideo#75]
Thanks a lot for your great work.
May I ask, what are the difference between  FLT, DIV and AES of InternVID dataset?

**Comment by yinanhe** [comment]
`DIV` is a subset sampled from the full `InternVid dataset` to maximize the diversity of video content; `FLT` is a subset of 10M selected through the calculation of `UMT-score` to filter video-text pairs with the highest similarity on `DIV`; `AES` is an 18M subset of videos selected through aesthetic score screening, recommended for tasks such as video generation training.

**Comment by Hambaobao** [comment]
Thanks a lot for your clarification.
