### ISSUE TITLE
aesthetics-18m

### ISSUE THREAD

**Issue by rese1f** [OpenGVLab/InternVideo#76]
Hi, seems like the link is broken, where I can find this subset?

”We release a subset [InternVid-Aesthetics-18M](https://huggingface.co/datasets/OpenGVLab/InternVid/viewer/InternVid-10M/AES). It consists of 18 million video clips that have been assigned high aesthetic scores.”

**Comment by yinanhe** [comment]
Sorry, there was an error in our naming. Actually, the file contains nearly 18 million lines. The correct link is: https://huggingface.co/datasets/OpenGVLab/InternVid/viewer/InternVid-10M-AES
