### ISSUE TITLE
Video links for Instruction Videos 

### ISSUE THREAD

**Issue by hainow** [OpenGVLab/InternVideo#84]
Thank you for releasing the [Instruction data](https://github.com/OpenGVLab/InternVideo/tree/main/Data/instruction_data) 

However, when I see the paths of the videos, I am not sure how to translate it to any downloadable links such as Youtube ID, e.g. 
`000051_000100/1066673749.mp4`, `000001_000050/1066685371.mp4`, ... 

Could you please help?

**Comment by shepnerd** [comment]
These videos are sourced from WebVid, originally from ShutterStock (with visible watermarks). So you can either download them from ShutterStock, or some volunteering work as [here](https://opendatalab.com/OpenDataLab/WebVid-2M).

**Comment by hainow** [comment]
thank you @shepnerd very much!
