### ISSUE TITLE
notebook

### ISSUE THREAD

**Issue by betterze** [OpenGVLab/InternVideo#86]
Dear InternVideo team,

Is there a notebook to show how to load the model and extract video feature? Thx a lot.

Best Wishes,
Zongze

**Comment by Arseny5** [comment]
Hello! You can find it in initial files on HF https://huggingface.co/OpenGVLab/ViCLIP/blob/main/demo.ipynb

**Comment by Arseny5** [comment]
> Dear InternVideo team,
> 
> Is there a notebook to show how to load the model and extract video feature? Thx a lot.
> 
> Best Wishes, Zongze

Hello! You can find it in initial files on HF https://huggingface.co/OpenGVLab/ViCLIP/blob/main/demo.ipynb

**Comment by betterze** [comment]
Thx for your reply. But the link is broken, could you update the link? Thx

**Comment by Arseny5** [comment]
> Thx for your reply. But the link is broken, could you update the link? Thx

GitHub - https://github.com/OpenGVLab/InternVideo/blob/main/Data/InternVid/demo.ipynb
Or HF - https://huggingface.co/OpenGVLab/ViCLIP/blob/main/demo.ipynb

**Comment by betterze** [comment]
Thx a lot, it works now. Could you tell me how many frames it can process? I do not find this number in the paper. If I provide 60 frames to it, can I get a continuous 60 frame video embedding from it? Thx a lot

**Comment by Arseny5** [comment]
> Thx a lot, it works now. Could you tell me how many frames it can process? I do not find this number in the paper. If I provide 60 frames to it, can I get a continuous 60 frame video embedding from it? Thx a lot

As I know, it's 8 frames. In demo notebook of ViClip you can find this function, where video processor select first 8 frames of input video:

```
def frames2tensor(vid_list, fnum=8, target_size=(224, 224), device=torch.device('cuda')):
    assert(len(vid_list) >= fnum)
    step = len(vid_list) // fnum
    vid_list = vid_list[::step][:fnum]
    vid_list = [cv2.resize(x[:,:,::-1], target_size) for x in vid_list]
    vid_tube = [np.expand_dims(normalize(x), axis=(0, 1)) for x in vid_list]
    vid_tube = np.concatenate(vid_tube, axis=1)
    vid_tube = np.transpose(vid_tube, (0, 1, 4, 2, 3))
    vid_tube = torch.from_numpy(vid_tube).to(device, non_blocking=True).float()
    return vid_tube
```

**Comment by betterze** [comment]
get it. thx a lot.

**Comment by EmreOzkose** [comment]
Authors also mention that 4 or 8 video frames work best:
![image](https://github.com/OpenGVLab/InternVideo/assets/17765576/5f7cb07d-a24a-4728-b889-1468523a42e7)

The point is that, is it necessary to re-trained model for different video frame numbers? I think yes, if so, did authors train 3 different model for 4/8/16 ?
