### ISSUE TITLE
Hope for the release of fine-tuned video retrieval checkpoint

### ISSUE THREAD

**Issue by oenewbee** [OpenGVLab/InternVideo#9]
Hi~ Thank you for your awesome work!

But in Video-Text-Retrieval task, till now only the pre-trained ViT weights of CLIP can be reached, and when will the fine-tuned video retrieval checkpoint be released? We all hore for it~

**Comment by yinanhe** [comment]
Hi, you can download our fine-tuned checkpoints by filling out this [form](https://wenjuan.feishu.cn/m?t=syQjww7QWNJi-jk5u).

**Comment by oenewbee** [comment]
> Hi, you can download our fine-tuned checkpoints by filling out this [form](https://wenjuan.feishu.cn/m?t=syQjww7QWNJi-jk5u).

Thanks very much for your opening these checkpoints~ But the checkpoint of MSR-VTT in retrieval task seems to be unreachable, when I enter the link, it shows 'This XML file does not appear to have any style information associated with it'. Maybe there exists some error?

**Comment by igodogi** [comment]
> > Hi, you can download our fine-tuned checkpoints by filling out this [form](https://wenjuan.feishu.cn/m?t=syQjww7QWNJi-jk5u).
> 
> Thanks very much for your opening these checkpoints~ But the checkpoint of MSR-VTT in retrieval task seems to be unreachable, when I enter the link, it shows 'This XML file does not appear to have any style information associated with it'. Maybe there exists some error?

Same issue

**Comment by yinanhe** [comment]
Thanks for pointing out this issue! We have already fixed the link for the checkpoint of MSR-VTT in the retrieval task. @oenewbee @igodogi
