### ISSUE TITLE
When will be InternVideo2 released

### ISSUE THREAD

**Issue by jpWang** [OpenGVLab/InternVideo#93]
Thanks for your great works~
And I just want to ask that is there a release schedule for InternVideo2?

**Comment by shepnerd** [comment]
Thank you for your interest. Please check [here](https://github.com/OpenGVLab/InternVideo/tree/main/InternVideo2) for code. We released 1B model at [here](https://huggingface.co/OpenGVLab/InternVideo2/blob/main/InternVideo2-stage2_1b-224p-f4.pt).
