### ISSUE TITLE
Do you have plans to release all the captions of InternVid?

### ISSUE THREAD

**Issue by yellow-binary-tree** [OpenGVLab/InternVideo#95]
As described in the paper, there are 234M clips in the InternVid dataset in all, but the size of the largest subset which is publicly available is only 18M. 
Do you have plans to release all the captions? Or can you release a subset of densely annotated videos (e.g., 1M videos, but with caption of all clips, so we can study the ordering of clips in the same video)

**Comment by aiPenguin** [comment]
I was going to ask the same question.

InternVid is a valuable dataset. But for now, only a small subset is released. 
It will be greatly helpful if the full dataset can released. A huge high-quality text-video dataset is in high demand.
Do you have any further release plans?

Thx.

**Comment by shepnerd** [comment]
Our team is preparing it. However, due to our tight schedule, the precise release date for the full version is currently uncertain.

**Comment by shepnerd** [comment]
Apologies for the delayed response. You can access the complete version of InternVid [here](https://huggingface.co/datasets/OpenGVLab/InternVid-Full).
