### ISSUE TITLE
is there a pretrain model release schedule for InternVideo2?

### ISSUE THREAD

**Issue by 1093842024** [OpenGVLab/InternVideo#98]
specially the stage 2, multimodel align trained models weight.
hope to get your update

**Comment by shepnerd** [comment]
Thank you for your interest. Please check [here](https://github.com/OpenGVLab/InternVideo/tree/main/InternVideo2/multi_modality) for code. We released 1B model at [here](https://huggingface.co/OpenGVLab/InternVideo2/blob/main/InternVideo2-stage2_1b-224p-f4.pt).
